remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache    # Required for minimal-mistakes

# Theme-specific settings
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
title: "Your Site Title"
subtitle: "Your Subtitle"
name: "Your Name"
description: "Your site description."
url: # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. "/blog"

# Author settings
author:
  name: "Your Name"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Your bio"
  location: "Your Location"

# Site Layout
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Build settings
markdown: kramdown

# Directory settings
layouts_dir: _layouts
posts_dir: posts

exclude:
  - venv/
  - .venv/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - generate_blog.py
  - requirements.txt
  - .git/
  - .github/
  - __pycache__/
  - "*.pyc"

keep_files:
  - .git
  - .gitignore

safe: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata 