theme: jekyll-theme-cayman

title: "Your Site Title"
description: "Your site description"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-sitemap

# Directory settings
layouts_dir: _layouts
posts_dir: posts

exclude:
  - venv/
  - .venv/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - generate_blog.py
  - requirements.txt
  - .git/
  - .github/
  - __pycache__/
  - "*.pyc"

keep_files:
  - .git
  - .gitignore

safe: true 