remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-sitemap

# Theme-specific settings
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
title: "DevOps"
subtitle: "Subtitle"
name: "Andrei"
description: "All day DevOps -> just figuring it out"
url: # your site's url
baseurl: # leave empty if not needed

# Author settings
author:
  name: "Andrei"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "DevOps by day, tech avid by night"
  location: "Timisoara"

# Site Layout
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Build settings
markdown: kramdown

# Directory settings
layouts_dir: _layouts
posts_dir: posts

exclude:
  - venv/
  - .venv/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - generate_blog.py
  - requirements.txt
  - .git/
  - .github/
  - __pycache__/
  - "*.pyc"

keep_files:
  - .git
  - .gitignore

safe: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata 