name: Generate and Post Blog

on:
  schedule:
    - cron: "0 8,12,18 * * *"  # Runs at 08:00, 12:00, and 18:00 UTC daily
  workflow_dispatch:  # Allows manual runs

jobs:
  generate_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Clean up and Set Up Virtual Environment
        run: |
          rm -rf venv
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install openai pyyaml

      - name: Ensure Script is Executable
        run: chmod +x generate_blog.py

      - name: Generate Blog Posts
        run: |
          source venv/bin/activate
          python generate_blog.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated blog post for $(date)" || echo "No changes to commit"
          git push || echo "No changes to push"
