name: Generate and Post Blog

on:
  schedule:
    - cron: "0 8,12,18 * * *"  # Runs at 8am, 12pm, and 6pm UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate_post:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for git operations

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate Blog Posts
        run: python generate_blog.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Build Site
        run: |
          bundle install
          bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated blog post for $(date)" || echo "No changes to commit"
          git push || echo "No changes to push"
