name: Generate and Post Blog

on:
  schedule:
    - cron: "0 8,12,18 * * *"  # Runs at 08:00, 12:00, and 18:00 UTC daily
  workflow_dispatch:  # Allows manual runs

jobs:
  generate_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'  # Enable pip caching

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai pyyaml

      - name: Install Jekyll Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Generate Blog Posts
        run: python generate_blog.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated blog post for $(date)" || echo "No changes to commit"
          git push || echo "No changes to push"
